export const listNav = [
  'tentang femmy',
  'produk',
  'tips & trik',
  'temukan femmy',
  'femmy reseller',
  'konsultasi',
];
// sementara
export const produk = [
  {
    judul: 'Femmy Trimune',
    slug: 'femmy-trimune',
    harga: 20000,
    rating: 4,
    image: '/images/produk/estrocal 6.png',
    imageDetail: '/images/produk/estrocal 6 (1).png',
    content: `<span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Detail Isi:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">6 sachet @3,2gr</p><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Suplemen Kesehatan yang bekerja sebagai immunomodulator effervescent dengan kandungan triple action (Echinachea, Vitamin C dan Zinc) dengan rasa yang enak untuk membantu memelihara kesehatan tubuh dan mengurangi pilek dengan rasa yang enak.</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Komposisi:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Echinacea Purpurea Herba Extract 200mg, Vitamin C 250mg, Zinc 5mg</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Petunjuk penggunaan:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Larutan 1 Sachet Femmy Trimune dengan 300ml air dingin, lalu diaduk sampai larut.</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Aturan Pakai:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Dewasa 1-3x sehari 1 Sachet: Anak - anak {'>'}6 tahun: 1x sehari</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Perhatian:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Aman dikonsumsi penderita diabetes, kolestrol, darah tinggi dan lambung. Tidak Aman dikonsumsi oleh ibu Hamil.</p>`,
  },
  {
    judul: 'Femmy Estrocal',
    slug: 'femmy-estrocal',
    harga: 50000,
    rating: 4,
    image: '/images/produk/estrocal 1.png',
    imageDetail: '/images/produk/estrocal 6 (2).png',
    content: `<span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Detail Isi:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Isi 12 stickpack @7gr</p><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Suplemen Kesehatan Tulang dan Sendi rasa Yoghurt dengan kandungan tinggi kalsium (500mg) , Glucosamine (250mg) dan Vitamin D3 yang lengkap untuk membantu memelihara kesehatan tulang dan sendi.</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Komposisi:</span><ol classname="list-decimal pl-4"><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Tinggi Kalsium (500mg) untuk meningkatkan kekuatan dan kepadatan Tulang</li><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Glucosamine (250gr) untuk menjaga kesehatan sendi dan mengurangi peradangan pada sendi</li><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Vitamin D3 bekerja untuk membantu penyerapan kalsium</li></ol><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Petunjuk Penggunaan:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Larutkan 1 stickpack dgn 300ml air dingin, aduk hingga rata</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Aturan Pakai:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Dewasa 1x sehari 1 stickpack</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Note:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Aman dikonsumsi penderita diabetes, kolestrol, darah tinggi dan lambung. Tidak boleh dikonsumsi oleh Ibu Hamil & menyusui.</p>`,
  },
  {
    judul: 'Femmy Fiber',
    slug: 'femmy-fiber',
    harga: 100000,
    rating: 4,
    image: '/images/produk/estrocal 2.png',
    imageDetail: '/images/produk/estrocal 6 (3).png',
    content: `<span className='block text-femmy-pdark text-[16px] text-sans font-bold'>Detail Isi:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Isi 7 Stickpack @15gram</p><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Minuman Tinggi serat dan rendah kalori rasa Mix Berry dengan kandungan Vit C dan D untuk memenuhi kebutuhan serat harian, membantu menurunkan berat badan serta menjaga berat badan tetap ideal.</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Komposisi:</span><ol classname="list-decimal pl-4"><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Menggunakan Pemanis Alami (Stevia)</li><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Rendah Kalori (60 Kkal)</li><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Enzim Lipase & Garcinia : Membantu menahan nafsu makan dan meningkatkan pembakaran lemak</li><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Physilium Husk : serat penuh untuk membantu konstipasi dan menurunkan kolestrol</li></ol><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Petunjuk penggunaan:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Larutkan 1 stickpack dgn 150ml air, aduk hingga rata</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Aturan Pakai:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Dewasa 1x sehari 1 stickpack (untuk hasil yang lebih maksimal 2x)</p><span className='block text-femmy-pdark text-[16px] text-sans font-bold'>Note :</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4"> Aman dikonsumsi penderita kolestrol, darah tinggi dan lambung. Tidak boleh dikonsumsi oleh penderita diabetes karena bisa menurunkan kadar gula darah secara double bersamaan dengan obat. Tidak boleh dikonsumsi oleh ibu hamil & menyusui.</p>`,
  },
  {
    judul: 'Femmy Skin',
    slug: 'femmy-skin',
    harga: 100000,
    rating: 4,
    image: '/images/produk/estrocal 5.png',
    imageDetail: '/images/produk/estrocal 6 (4).png',
    content: `<span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Detail Isi:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Isi 12 stickpack @7gr</p><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Collagen Drink dengan esktrak Hytolive®, esktrak Kiwi dan Vitamin E untuk memelihara kesehatan kulit, meningkatkan elastisitas kulit, regenerasi sel kulit, mengurangi kerutan, dan mengurangi rontok.</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Komposisi:</span><ol classname="list-decimal pl-4"><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Collagen 1.000mg : meningkatkan elastisitas kulit, mengurangi rambut rontok</li><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Vitamin E : menjaga hidrasi kulit dan regenerasi sel</li><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Kiwi fruit extract : sumber vitamin C dan antioksidant</li><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Olive extract : mempercepat penyembuhan bekas luka, mengurangi kerutan dan garis halus.</li></ol><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Petunjuk penggunaan:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Larutkan 1 stickpack dgn 300ml air, aduk hingga rata</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Aturan Pakai:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Dewasa 2x sehari 1 stickpack (untuk hasil yang lebih maksimal)</p>`,
  },
  {
    judul: 'Femmy Mensana',
    slug: 'femmy-mensana',
    harga: 25000,
    rating: 4,
    image: '/images/produk/estrocal 3.png',
    imageDetail: '/images/produk/estrocal 6 (5).png',
    content: `<span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Detail Isi:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Isi 12 stickpack @7gr</p><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Minuman Kesehatan dengan kandungan alami untuk membantu melancarkan dan meredakan nyeri pada saat menstruasi, rasa tamarin yang enak dan menyegarkan.</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Komposisi:</span><ol classname="list-decimal pl-4"><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Agni casti dan tamarin: meregulasi hormon dan mengatur kontraksi rahim selama periode menstruasi</li><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Kunyit dan Jahe Merah: sebagai analgesik dan anti inflamasi</li><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Guarana: bekerja sebagai kafein alami memberikan energi</li></ol><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Petunjuk Penggunaan:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Larutkan 1 stickpack dgn 300ml air, aduk hingga rata.</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Aturan Pakai:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Dewasa 2x sehari 1 stickpack.</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Perhatian:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Aman dikonsumsi penderita diabetes, kolestrol dan lambung. Tidak boleh dikonsumsi oleh penderita darah tinggi.</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Note:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Aman dikonsumsi penderita diabetes, kolestrol dan lambung. Tidak boleh dikonsumsi oleh penderita darah tinggi.</p>`,
  },
  {
    judul: 'Femmy Vit D3',
    slug: 'femmy-vit-d3',
    harga: 25000,
    rating: 4,
    image: '/images/produk/estrocal 4.png',
    imageDetail: '/images/produk/estrocal 6 (6).png',
    content: `<span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Detail Isi:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">IsIsi 1 strip @10 tablet salut selaput</p><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Femmy D3 1.000 IU merupakan Vit D3 dengan dosis tepat untuk dikonsumsi setiap hari, dengan mini tablet yang memberikan banyak manfaat yaitu Meningkatkan imun tubuh, Menjaga kesehatan tulang, mencegah osteoporosis, dan memelihara kesehatan jantung.</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Komposisi:</span><ol classname="list-decimal pl-4"><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Membantu menjaga kesehatan tulang</li><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Membantu menjaga kesehatan tulang</li><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Membantu menjaga kekuatan otot</li><li classname="text-femmy-pdark text-[16px] text-sans mb-4">Membantu saraf membawa pesan antara otak dan tubuh</li></ol><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Komposisi:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Vitamin D3 1000 IU.</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Aturan Pakai:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Dewasa 1x sehari 1 tablet setelah makan pagi.</p><span classname="block text-femmy-pdark text-[16px] text-sans font-bold">Perhatian:</span><p classname="block text-femmy-pdark text-[16px] text-sans mb-4">Aman dikonsumsi penderita diabetes, kolestrol, darah tinggi dan lambung. Aman dikonsumsi oleh ibu Hamil.</p>`,
  },
];
